// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpUIaRJgWVJMWzm6c8bZON4cbxw8XuxK4',
    appId: '1:290354325803:web:c3d9f8482332f4e24a7d6e',
    messagingSenderId: '290354325803',
    projectId: 'biblia-348d5',
    authDomain: 'biblia-348d5.firebaseapp.com',
    storageBucket: 'biblia-348d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEIi2H-0KyBH-fggtptlr1wsj6iR-DQHc',
    appId: '1:290354325803:android:59624e183e89c2874a7d6e',
    messagingSenderId: '290354325803',
    projectId: 'biblia-348d5',
    storageBucket: 'biblia-348d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPbY8LNFx3Ui2VOl7DS7D6yZkSsoQVeqQ',
    appId: '1:290354325803:ios:2e8c7f662131a61b4a7d6e',
    messagingSenderId: '290354325803',
    projectId: 'biblia-348d5',
    storageBucket: 'biblia-348d5.firebasestorage.app',
    iosBundleId: 'com.example.bibliaEstudosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPbY8LNFx3Ui2VOl7DS7D6yZkSsoQVeqQ',
    appId: '1:290354325803:ios:2e8c7f662131a61b4a7d6e',
    messagingSenderId: '290354325803',
    projectId: 'biblia-348d5',
    storageBucket: 'biblia-348d5.firebasestorage.app',
    iosBundleId: 'com.example.bibliaEstudosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpUIaRJgWVJMWzm6c8bZON4cbxw8XuxK4',
    appId: '1:290354325803:web:61e94cc6d2a0870c4a7d6e',
    messagingSenderId: '290354325803',
    projectId: 'biblia-348d5',
    authDomain: 'biblia-348d5.firebaseapp.com',
    storageBucket: 'biblia-348d5.firebasestorage.app',
  );

}